### ISSUE TITLE
Unnecessary re-renders using useQueryParams

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#41] opened 2020-01-09 23:25 UTC
Hey again @kyeotic 👋 

I am currently investigating some performance issues we are experiencing when changing URL parameters with `useQueryParams`.

I am finding issues within our own code but also what I think could be issues in `raviger`.

For instance, I have found this and I am not sure if it's an issue or a feature request: [Code Sandebox](https://codesandbox.io/s/strange-boyd-2ezbk)

Whenever setting the same values for the parameters, the `RouterContext.Provider` value changes, causing the components consuming the context to re-render.

The problem is here: [router.js#L32](https://github.com/kyeotic/raviger/blob/master/src/router.js#L32)

Each render loop generates a new object reference passed to the context provider, the value is not memoized with `useMemo`, and there is nothing that checks for deep equality of the parameters to prevent passing a new object reference either.

Additionally, pushing the same query params still pushes a new history state, and I am not sure if that is expected or a bug?

**Comment by kyeotic** [comment] 2020-01-09 23:50
Yea, thats definitely an issue. I'll get that fixed.

**Comment by kyeotic** [comment] 2020-01-10 00:51
This one is a bit sticky. Splitting up the context or memozing causes #34 to regress for reasons I don't yet understand.

**Comment by yenoiwesa** [comment] 2020-01-10 02:16
Well I think that's actually good because I was going to raise an issue for that too :-/

Using the current latest version of the library, which includes the fix for #34, I am seeing that the routes re-render multiple times before they reach their stable `path` state, with multiple wrong values in between (like the value mentioned in #34).

I am using https://github.com/welldone-software/why-did-you-render to investigate this and see what caused our components to re-render.

**Comment by kyeotic** [comment] 2020-01-10 02:36
That looks like a really handy library, unfortunately it didn't tell me what was causing my mystery re-render.

![image](https://user-images.githubusercontent.com/1187432/72121116-f61ee500-330e-11ea-9577-e025ee84dfdb.png)

**Comment by kyeotic** [comment] 2020-01-10 02:38
I'm tempted to publish what I have so far; even though its not perfect its a big improvement. Any opinion @yenoiwesa ?

**Comment by kyeotic** [comment] 2020-01-10 03:00
published under `raviger@1.1.2`

**Comment by yenoiwesa** [comment] 2020-01-10 03:14
Yes that sounds like a plan, I intend to do a bit more testing but I might hand over to @micmcg eventually ;-)

**Comment by kyeotic** [comment] 2020-01-10 03:16
Ok. Keep me posted on how this update affects the issues you are seeing. I'm happy to keep helping here

**Comment by yenoiwesa** [comment] 2020-01-10 03:49
So I just upgraded to `raviger@1.1.2` to perform a test and clearly bug #34 has come back. Breaks our entire app.

This is the route re-render when clicking on a link to a different section, and the URL should go from `/overview` to `/commits` but it goes to `/<id>/commits` instead:

![image](https://user-images.githubusercontent.com/1464666/72124285-47cf7a00-33b8-11ea-8e28-ce91a50a455b.png)

**Comment by kyeotic** [comment] 2020-01-10 03:53
Well that's no good. I have a test case for that but its passing. I'll try to reproduce it

**Comment by kyeotic** [comment] 2020-01-10 03:57
@yenoiwesa [The deep link example](https://github.com/kyeotic/raviger/blob/master/example/src/App.js#L13) and [this test](https://github.com/kyeotic/raviger/blob/master/test/path.spec.js#L79) are both passing. I dont understand when its happening, can you provide a sandbox reproduction for this?

**Comment by yenoiwesa** [comment] 2020-01-10 03:59
@kyeotic I'll try!

**Comment by kyeotic** [comment] 2020-01-10 04:05
You're going to have a hard time, I accidentally unpublished that version instead of deprecating it 🤦‍♂

**Comment by kyeotic** [comment] 2020-01-10 04:07
I added that `useMemo` fix you commented on and published under `raviger@1.1.3-beta.1` (its a beta tag)

**Comment by yenoiwesa** [comment] 2020-01-10 04:12
> You're going to have a hard time, I accidentally unpublished that version instead of deprecating it 🤦‍♂

Ahah that's fine, it's just on my local branch for now I have not broken the product for the whole team yet :-P

**Comment by kyeotic** [comment] 2020-01-10 04:16
I just meant you'd have a hard time making a sandbox repo with the version unpublished from npm.

I've tried a few different setup and I still cant get the failure from #34. I've got to handle something else, but if you get me a repro tonight I will make sure it gets fixed.

**Comment by kyeotic** [comment] 2020-01-10 19:27
@yenoiwesa Im going to be travelling this weekend, so I will be unusually unresponsive.

**Comment by yenoiwesa** [comment] 2020-01-12 22:31
No worries @kyeotic. I couldn't get to the bottom of this issue and get a reproduction for it unfortunately. I'll leave this issue on the side for now as I need to progress on some other task, but I or @micmcg will come back to it hopefully during this week!

**Comment by kyeotic** [comment] 2020-01-13 16:47
Ok, I'm going to leave this as a beta for now, just in case the bug is in raviger. I'll have some more time tomorrow to investigate again.

**Comment by kyeotic** [comment] 2020-01-17 21:31
Hey @yenoiwesa and @micmcg, I have been unable to reproduce the #34 despite several different attempts. At this point, barring a reproducible bug, I am tempted to say the bug is in your end and promote the beta tomorrow; it has a huge re-rendering reduction and I don't have a good reason to sit on it.

**Comment by yenoiwesa** [comment] 2020-01-19 22:01
Hey @kyeotic, that's fair.

We did not have time at all this week to investigate the issue further unfortunately. It's definitely something we want to do but we have pressing deadlines at the moment.

Our builds use fixed versions with package-lock either way so it would be fine to release a patch if you feel that's better.

Thanks a lot for your help, will keep you updated when we find something!

**Comment by kyeotic** [comment] 2020-01-22 06:36
I've published the change under `1.2.0`. I'll leave this open until you guys figure out whether the bug is on raviger's side or yours.

**Comment by kyeotic** [comment] 2020-02-05 17:25
@yenoiwesa Another user had an issue (#46) with unwanted navigation due to a `setQueryParams` call inside a `useEffect`. It sounded like it might be similar to this issue, thought it might help you with a reproduction.

**Comment by kyeotic** [comment] 2020-02-25 06:56
I'm going to close this @yenoiwesa, we can re-open it if you come back to it

**Closed by kyeotic** 2020-02-25 06:56 UTC
Labels: :bug: Bug

**Comment by yenoiwesa** [comment] 2020-02-25 07:13
@kyeotic fair. We unfortunately have had no time to go back to that problem yet as we have been in release mode for the past two months. We are still on the older version of the library that didn't have the issue we encountered during the upgrade.

We will surely come back to it at some point when we attempt to upgrade again.

Thanks for your help and sorry about our lack of responsiveness on this.

**Comment by kyeotic** [comment] 2020-02-25 17:06
No worries at all, I totally understand. Hope your releases are all going smoothly :)
